/**
 * AudienceAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('AudienceAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    expect(mod.AudienceAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(instance).toBeTruthy();
  });

  it('should have createPoll method', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(typeof instance.createPoll).toBe('function');
  });

  it('should have getPoll method', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(typeof instance.getPoll).toBe('function');
  });

  it('should have closePoll method', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(typeof instance.closePoll).toBe('function');
  });

  it('should have getPollResults method', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(typeof instance.getPollResults).toBe('function');
  });

  it('should have vote method', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(typeof instance.vote).toBe('function');
  });

  it('should have createQA method', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(typeof instance.createQA).toBe('function');
  });

  it('should have getQA method', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(typeof instance.getQA).toBe('function');
  });

  it('should have closeQA method', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(typeof instance.closeQA).toBe('function');
  });

  it('should have submitQuestion method', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(typeof instance.submitQuestion).toBe('function');
  });

  it('should have answerQuestion method', async () => {
    const mod = await import('packages/sdk-typescript/@/audience');
    const instance = new mod.AudienceAPI();
    expect(typeof instance.answerQuestion).toBe('function');
  });
});
