/**
 * ChaptersAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('ChaptersAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    expect(mod.ChaptersAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(instance).toBeTruthy();
  });

  it('should have generate method', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(typeof instance.generate).toBe('function');
  });

  it('should have createSet method', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(typeof instance.createSet).toBe('function');
  });

  it('should have getSet method', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(typeof instance.getSet).toBe('function');
  });

  it('should have updateSet method', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(typeof instance.updateSet).toBe('function');
  });

  it('should have removeSet method', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(typeof instance.removeSet).toBe('function');
  });

  it('should have listSets method', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(typeof instance.listSets).toBe('function');
  });

  it('should have getDefaultSet method', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(typeof instance.getDefaultSet).toBe('function');
  });

  it('should have duplicateSet method', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(typeof instance.duplicateSet).toBe('function');
  });

  it('should have addChapter method', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(typeof instance.addChapter).toBe('function');
  });

  it('should have getChapter method', async () => {
    const mod = await import('packages/sdk-typescript/@/chapters');
    const instance = new mod.ChaptersAPI();
    expect(typeof instance.getChapter).toBe('function');
  });
});
