/**
 * CollabAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('CollabAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    expect(mod.CollabAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(instance).toBeTruthy();
  });

  it('should have createRoom method', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(typeof instance.createRoom).toBe('function');
  });

  it('should have getRoom method', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(typeof instance.getRoom).toBe('function');
  });

  it('should have updateRoom method', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(typeof instance.updateRoom).toBe('function');
  });

  it('should have closeRoom method', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(typeof instance.closeRoom).toBe('function');
  });

  it('should have archiveRoom method', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(typeof instance.archiveRoom).toBe('function');
  });

  it('should have listRooms method', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(typeof instance.listRooms).toBe('function');
  });

  it('should have getJoinToken method', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(typeof instance.getJoinToken).toBe('function');
  });

  it('should have listParticipants method', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(typeof instance.listParticipants).toBe('function');
  });

  it('should have getParticipant method', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(typeof instance.getParticipant).toBe('function');
  });

  it('should have updateParticipant method', async () => {
    const mod = await import('packages/sdk-typescript/@/collab');
    const instance = new mod.CollabAPI();
    expect(typeof instance.updateParticipant).toBe('function');
  });
});
