/**
 * ConnectAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('ConnectAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    expect(mod.ConnectAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(instance).toBeTruthy();
  });

  it('should have list method', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(typeof instance.list).toBe('function');
  });

  it('should have get method', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(typeof instance.get).toBe('function');
  });

  it('should have enable method', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(typeof instance.enable).toBe('function');
  });

  it('should have disable method', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(typeof instance.disable).toBe('function');
  });

  it('should have configure method', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(typeof instance.configure).toBe('function');
  });

  it('should have testConnection method', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(typeof instance.testConnection).toBe('function');
  });

  it('should have listWebhooks method', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(typeof instance.listWebhooks).toBe('function');
  });

  it('should have createWebhook method', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(typeof instance.createWebhook).toBe('function');
  });

  it('should have updateWebhook method', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(typeof instance.updateWebhook).toBe('function');
  });

  it('should have removeWebhook method', async () => {
    const mod = await import('packages/sdk-typescript/@/connect');
    const instance = new mod.ConnectAPI();
    expect(typeof instance.removeWebhook).toBe('function');
  });
});
