/**
 * CreatorAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('CreatorAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    expect(mod.CreatorAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    const instance = new mod.CreatorAPI();
    expect(instance).toBeTruthy();
  });

  it('should have getProfile method', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    const instance = new mod.CreatorAPI();
    expect(typeof instance.getProfile).toBe('function');
  });

  it('should have updateProfile method', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    const instance = new mod.CreatorAPI();
    expect(typeof instance.updateProfile).toBe('function');
  });

  it('should have getRevenue method', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    const instance = new mod.CreatorAPI();
    expect(typeof instance.getRevenue).toBe('function');
  });

  it('should have listSubscriptions method', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    const instance = new mod.CreatorAPI();
    expect(typeof instance.listSubscriptions).toBe('function');
  });

  it('should have listTips method', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    const instance = new mod.CreatorAPI();
    expect(typeof instance.listTips).toBe('function');
  });

  it('should have createTipJar method', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    const instance = new mod.CreatorAPI();
    expect(typeof instance.createTipJar).toBe('function');
  });

  it('should have listPayouts method', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    const instance = new mod.CreatorAPI();
    expect(typeof instance.listPayouts).toBe('function');
  });

  it('should have requestPayout method', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    const instance = new mod.CreatorAPI();
    expect(typeof instance.requestPayout).toBe('function');
  });

  it('should have getAnalytics method', async () => {
    const mod = await import('packages/sdk-typescript/@/creator');
    const instance = new mod.CreatorAPI();
    expect(typeof instance.getAnalytics).toBe('function');
  });
});
