/**
 * DesktopAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('DesktopAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    expect(mod.DesktopAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(instance).toBeTruthy();
  });

  it('should have getInfo method', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(typeof instance.getInfo).toBe('function');
  });

  it('should have getStatus method', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(typeof instance.getStatus).toBe('function');
  });

  it('should have listDevices method', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(typeof instance.listDevices).toBe('function');
  });

  it('should have configure method', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(typeof instance.configure).toBe('function');
  });

  it('should have getConfig method', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(typeof instance.getConfig).toBe('function');
  });

  it('should have getLogs method', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(typeof instance.getLogs).toBe('function');
  });

  it('should have getPerformance method', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(typeof instance.getPerformance).toBe('function');
  });

  it('should have checkForUpdate method', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(typeof instance.checkForUpdate).toBe('function');
  });

  it('should have installUpdate method', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(typeof instance.installUpdate).toBe('function');
  });

  it('should have restart method', async () => {
    const mod = await import('packages/sdk-typescript/@/desktop');
    const instance = new mod.DesktopAPI();
    expect(typeof instance.restart).toBe('function');
  });
});
