/**
 * DistributionAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('DistributionAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    expect(mod.DistributionAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(instance).toBeTruthy();
  });

  it('should have listDestinations method', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(typeof instance.listDestinations).toBe('function');
  });

  it('should have getDestination method', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(typeof instance.getDestination).toBe('function');
  });

  it('should have addDestination method', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(typeof instance.addDestination).toBe('function');
  });

  it('should have updateDestination method', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(typeof instance.updateDestination).toBe('function');
  });

  it('should have removeDestination method', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(typeof instance.removeDestination).toBe('function');
  });

  it('should have startSimulcast method', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(typeof instance.startSimulcast).toBe('function');
  });

  it('should have stopSimulcast method', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(typeof instance.stopSimulcast).toBe('function');
  });

  it('should have getSimulcastStatus method', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(typeof instance.getSimulcastStatus).toBe('function');
  });

  it('should have schedulePost method', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(typeof instance.schedulePost).toBe('function');
  });

  it('should have listScheduledPosts method', async () => {
    const mod = await import('packages/sdk-typescript/@/distribution');
    const instance = new mod.DistributionAPI();
    expect(typeof instance.listScheduledPosts).toBe('function');
  });
});
