/**
 * DrmAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('DrmAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    expect(mod.DrmAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    const instance = new mod.DrmAPI();
    expect(instance).toBeTruthy();
  });

  it('should have createPolicy method', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    const instance = new mod.DrmAPI();
    expect(typeof instance.createPolicy).toBe('function');
  });

  it('should have getPolicy method', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    const instance = new mod.DrmAPI();
    expect(typeof instance.getPolicy).toBe('function');
  });

  it('should have listPolicies method', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    const instance = new mod.DrmAPI();
    expect(typeof instance.listPolicies).toBe('function');
  });

  it('should have updatePolicy method', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    const instance = new mod.DrmAPI();
    expect(typeof instance.updatePolicy).toBe('function');
  });

  it('should have removePolicy method', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    const instance = new mod.DrmAPI();
    expect(typeof instance.removePolicy).toBe('function');
  });

  it('should have getCertificate method', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    const instance = new mod.DrmAPI();
    expect(typeof instance.getCertificate).toBe('function');
  });

  it('should have issueLicense method', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    const instance = new mod.DrmAPI();
    expect(typeof instance.issueLicense).toBe('function');
  });

  it('should have revokeLicense method', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    const instance = new mod.DrmAPI();
    expect(typeof instance.revokeLicense).toBe('function');
  });

  it('should have listLicenses method', async () => {
    const mod = await import('packages/sdk-typescript/@/drm');
    const instance = new mod.DrmAPI();
    expect(typeof instance.listLicenses).toBe('function');
  });
});
