/**
 * EdgeAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('EdgeAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    expect(mod.EdgeAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(instance).toBeTruthy();
  });

  it('should have listNodes method', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(typeof instance.listNodes).toBe('function');
  });

  it('should have getNode method', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(typeof instance.getNode).toBe('function');
  });

  it('should have getNodeMetrics method', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(typeof instance.getNodeMetrics).toBe('function');
  });

  it('should have deployWorker method', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(typeof instance.deployWorker).toBe('function');
  });

  it('should have getWorker method', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(typeof instance.getWorker).toBe('function');
  });

  it('should have updateWorker method', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(typeof instance.updateWorker).toBe('function');
  });

  it('should have removeWorker method', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(typeof instance.removeWorker).toBe('function');
  });

  it('should have listWorkers method', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(typeof instance.listWorkers).toBe('function');
  });

  it('should have startWorker method', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(typeof instance.startWorker).toBe('function');
  });

  it('should have stopWorker method', async () => {
    const mod = await import('packages/sdk-typescript/@/edge');
    const instance = new mod.EdgeAPI();
    expect(typeof instance.stopWorker).toBe('function');
  });
});
