/**
 * EditorAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('EditorAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    expect(mod.EditorAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(instance).toBeTruthy();
  });

  it('should have createProject method', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(typeof instance.createProject).toBe('function');
  });

  it('should have getProject method', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(typeof instance.getProject).toBe('function');
  });

  it('should have updateProject method', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(typeof instance.updateProject).toBe('function');
  });

  it('should have removeProject method', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(typeof instance.removeProject).toBe('function');
  });

  it('should have listProjects method', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(typeof instance.listProjects).toBe('function');
  });

  it('should have duplicateProject method', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(typeof instance.duplicateProject).toBe('function');
  });

  it('should have addTrack method', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(typeof instance.addTrack).toBe('function');
  });

  it('should have updateTrack method', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(typeof instance.updateTrack).toBe('function');
  });

  it('should have removeTrack method', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(typeof instance.removeTrack).toBe('function');
  });

  it('should have addElement method', async () => {
    const mod = await import('packages/sdk-typescript/@/editor');
    const instance = new mod.EditorAPI();
    expect(typeof instance.addElement).toBe('function');
  });
});
