/**
 * GhostAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('GhostAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    expect(mod.GhostAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(instance).toBeTruthy();
  });

  it('should have start method', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(typeof instance.start).toBe('function');
  });

  it('should have get method', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(typeof instance.get).toBe('function');
  });

  it('should have update method', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(typeof instance.update).toBe('function');
  });

  it('should have stop method', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(typeof instance.stop).toBe('function');
  });

  it('should have pause method', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(typeof instance.pause).toBe('function');
  });

  it('should have resume method', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(typeof instance.resume).toBe('function');
  });

  it('should have override method', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(typeof instance.override).toBe('function');
  });

  it('should have listSuggestions method', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(typeof instance.listSuggestions).toBe('function');
  });

  it('should have acceptSuggestion method', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(typeof instance.acceptSuggestion).toBe('function');
  });

  it('should have rejectSuggestion method', async () => {
    const mod = await import('packages/sdk-typescript/@/ghost');
    const instance = new mod.GhostAPI();
    expect(typeof instance.rejectSuggestion).toBe('function');
  });
});
