/**
 * MarketplaceAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('MarketplaceAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    expect(mod.MarketplaceAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(instance).toBeTruthy();
  });

  it('should have list method', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(typeof instance.list).toBe('function');
  });

  it('should have get method', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(typeof instance.get).toBe('function');
  });

  it('should have install method', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(typeof instance.install).toBe('function');
  });

  it('should have uninstall method', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(typeof instance.uninstall).toBe('function');
  });

  it('should have listInstalled method', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(typeof instance.listInstalled).toBe('function');
  });

  it('should have publish method', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(typeof instance.publish).toBe('function');
  });

  it('should have update method', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(typeof instance.update).toBe('function');
  });

  it('should have deprecate method', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(typeof instance.deprecate).toBe('function');
  });

  it('should have getReviews method', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(typeof instance.getReviews).toBe('function');
  });

  it('should have addReview method', async () => {
    const mod = await import('packages/sdk-typescript/@/marketplace');
    const instance = new mod.MarketplaceAPI();
    expect(typeof instance.addReview).toBe('function');
  });
});
