/**
 * MeshAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('MeshAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    expect(mod.MeshAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(instance).toBeTruthy();
  });

  it('should have listRegions method', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(typeof instance.listRegions).toBe('function');
  });

  it('should have getRegion method', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(typeof instance.getRegion).toBe('function');
  });

  it('should have getRegionHealth method', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(typeof instance.getRegionHealth).toBe('function');
  });

  it('should have listPeers method', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(typeof instance.listPeers).toBe('function');
  });

  it('should have addPeer method', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(typeof instance.addPeer).toBe('function');
  });

  it('should have removePeer method', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(typeof instance.removePeer).toBe('function');
  });

  it('should have createPolicy method', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(typeof instance.createPolicy).toBe('function');
  });

  it('should have updatePolicy method', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(typeof instance.updatePolicy).toBe('function');
  });

  it('should have removePolicy method', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(typeof instance.removePolicy).toBe('function');
  });

  it('should have listPolicies method', async () => {
    const mod = await import('packages/sdk-typescript/@/mesh');
    const instance = new mod.MeshAPI();
    expect(typeof instance.listPolicies).toBe('function');
  });
});
