/**
 * NotificationsAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('NotificationsAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    expect(mod.NotificationsAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    const instance = new mod.NotificationsAPI();
    expect(instance).toBeTruthy();
  });

  it('should have list method', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    const instance = new mod.NotificationsAPI();
    expect(typeof instance.list).toBe('function');
  });

  it('should have get method', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    const instance = new mod.NotificationsAPI();
    expect(typeof instance.get).toBe('function');
  });

  it('should have markAsRead method', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    const instance = new mod.NotificationsAPI();
    expect(typeof instance.markAsRead).toBe('function');
  });

  it('should have markAllRead method', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    const instance = new mod.NotificationsAPI();
    expect(typeof instance.markAllRead).toBe('function');
  });

  it('should have archive method', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    const instance = new mod.NotificationsAPI();
    expect(typeof instance.archive).toBe('function');
  });

  it('should have remove method', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    const instance = new mod.NotificationsAPI();
    expect(typeof instance.remove).toBe('function');
  });

  it('should have getUnreadCount method', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    const instance = new mod.NotificationsAPI();
    expect(typeof instance.getUnreadCount).toBe('function');
  });

  it('should have getPreferences method', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    const instance = new mod.NotificationsAPI();
    expect(typeof instance.getPreferences).toBe('function');
  });

  it('should have updatePreferences method', async () => {
    const mod = await import('packages/sdk-typescript/@/notifications');
    const instance = new mod.NotificationsAPI();
    expect(typeof instance.updatePreferences).toBe('function');
  });
});
