/**
 * PhoneAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('PhoneAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    expect(mod.PhoneAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(instance).toBeTruthy();
  });

  it('should have listNumbers method', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(typeof instance.listNumbers).toBe('function');
  });

  it('should have getNumber method', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(typeof instance.getNumber).toBe('function');
  });

  it('should have searchAvailableNumbers method', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(typeof instance.searchAvailableNumbers).toBe('function');
  });

  it('should have purchaseNumber method', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(typeof instance.purchaseNumber).toBe('function');
  });

  it('should have updateNumber method', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(typeof instance.updateNumber).toBe('function');
  });

  it('should have releaseNumber method', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(typeof instance.releaseNumber).toBe('function');
  });

  it('should have makeCall method', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(typeof instance.makeCall).toBe('function');
  });

  it('should have getCall method', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(typeof instance.getCall).toBe('function');
  });

  it('should have listCalls method', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(typeof instance.listCalls).toBe('function');
  });

  it('should have updateCall method', async () => {
    const mod = await import('packages/sdk-typescript/@/phone');
    const instance = new mod.PhoneAPI();
    expect(typeof instance.updateCall).toBe('function');
  });
});
