/**
 * PipelineAPI Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('PipelineAPI', () => {
  it('should be importable', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    expect(mod.PipelineAPI).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(instance).toBeTruthy();
  });

  it('should have create method', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(typeof instance.create).toBe('function');
  });

  it('should have get method', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(typeof instance.get).toBe('function');
  });

  it('should have update method', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(typeof instance.update).toBe('function');
  });

  it('should have remove method', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(typeof instance.remove).toBe('function');
  });

  it('should have list method', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(typeof instance.list).toBe('function');
  });

  it('should have start method', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(typeof instance.start).toBe('function');
  });

  it('should have stop method', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(typeof instance.stop).toBe('function');
  });

  it('should have switchProtocol method', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(typeof instance.switchProtocol).toBe('function');
  });

  it('should have getHealth method', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(typeof instance.getHealth).toBe('function');
  });

  it('should have getIngestEndpoints method', async () => {
    const mod = await import('packages/sdk-typescript/@/pipeline');
    const instance = new mod.PipelineAPI();
    expect(typeof instance.getIngestEndpoints).toBe('function');
  });
});
